# Generated by Django 2.0.3 on 2018-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('questId', models.AutoField(primary_key=True, serialize=False)),
                ('questName', models.CharField(max_length=80)),
                ('categoryId', models.IntegerField()),
                ('levelId', models.IntegerField()),
                ('imageURL', models.URLField()),
                ('distance', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
