# Generated by Django 2.0.3 on 2018-03-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Quests',
        ),
    ]
