# Generated by Django 2.0.3 on 2018-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180331_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelId', models.AutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('locationDescription', models.TextField()),
                ('locationImageURL', models.URLField()),
                ('questId', models.IntegerField()),
                ('order', models.IntegerField()),
                ('isSecret', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='quests',
            old_name='description',
            new_name='questDescription',
        ),
        migrations.RenameField(
            model_name='quests',
            old_name='imageURL',
            new_name='questImageURL',
        ),
    ]
