# Generated by Django 2.0.3 on 2018-03-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180331_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quests',
            new_name='Quest',
        ),
    ]
