# Generated by Django 2.0.3 on 2018-03-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180331_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryId',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='levelId',
            new_name='level_id',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='levelName',
            new_name='level_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locationDescription',
            new_name='location_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locationId',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locationName',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='questDescription',
            new_name='quest_description',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='questId',
            new_name='quest_id',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='questName',
            new_name='quest_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='isSecret',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locationImageURL',
        ),
        migrations.RemoveField(
            model_name='location',
            name='questId',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='levelId',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='questImageURL',
        ),
        migrations.AddField(
            model_name='location',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_image_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='quest_id',
            field=models.ManyToManyField(to='landing.Quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='category_id',
            field=models.ManyToManyField(to='landing.Category'),
        ),
        migrations.AddField(
            model_name='quest',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Level'),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_image_URL',
            field=models.URLField(blank=True),
        ),
    ]
